id: I7F908834
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 14:57:33.460597
last_modified: 2023-02-08 14:57:33.460767
source_metadata:
  title: 'RK: Bodhisatvapiṭaka'
  language: en
bases:
  29A4:
    base_file: 29A4.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
